import { Platform, StatusBar, StyleSheet } from "react-native";

export const COLORS = {
  bg: "#EFE9D6",
  surface: "#FFFDF6",
  ink: "#2B3320",
  inkSoft: "#5B6650",
  primary: "#5C7A3E",
  primaryDark: "#3F5729",
  accent: "#C6852F",
  line: "#D9CFAE",
  danger: "#A5502E",
};

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: COLORS.bg, paddingTop: Platform.OS === "android" ? StatusBar.currentHeight : 0 },
  wrap: { padding: 16, paddingBottom: 48 },

  header: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-end", borderBottomWidth: 2, borderBottomColor: COLORS.ink, paddingBottom: 12, marginBottom: 16 },
  title: { fontSize: 26, fontWeight: "700", color: COLORS.ink },
  subtitle: { fontSize: 12, color: COLORS.inkSoft, marginTop: 2 },
  weatherMini: { flexDirection: "row", alignItems: "center", gap: 8, backgroundColor: COLORS.surface, borderWidth: 1, borderColor: COLORS.line, borderRadius: 4, paddingVertical: 6, paddingHorizontal: 10 },
  weatherIcon: { fontSize: 22 },
  weatherTemp: { fontSize: 14, fontWeight: "700", color: COLORS.ink },
  weatherSub: { fontSize: 11, color: COLORS.inkSoft },
  warningContainer: { marginBottom: 16, gap: 8 },
  warningBanner: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", backgroundColor: "#FDEBD0", borderWidth: 1, borderColor: COLORS.danger, borderRadius: 6, padding: 12 },
  warningBannerInner: { flexDirection: "row", alignItems: "center", gap: 12 },
  warningIcon: { fontSize: 24 },
  warningTitle: { fontSize: 14, fontWeight: "700", color: COLORS.danger, marginBottom: 2 },
  warningSub: { fontSize: 11, color: "#935116" },
  warningArrow: { fontSize: 20, color: COLORS.danger, fontWeight: "300" },

  monthNav: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 8 },
  navBtn: { width: 30, height: 30, borderWidth: 1, borderColor: COLORS.ink, borderRadius: 4, alignItems: "center", justifyContent: "center" },
  navBtnText: { fontSize: 16, color: COLORS.ink },
  monthLabel: { fontSize: 17, fontWeight: "700", color: COLORS.ink },

  weekRow: { flexDirection: "row", marginBottom: 4 },
  weekLabel: { flex: 1, textAlign: "center", fontSize: 11, color: COLORS.inkSoft },

  grid: { flexDirection: "row", flexWrap: "wrap", backgroundColor: COLORS.surface, borderWidth: 1, borderColor: COLORS.line },
  cell: { width: "14.28%", height: 68, borderWidth: 0.5, borderColor: COLORS.line, padding: 4 },
  cellEmpty: { width: "14.28%", height: 68, borderWidth: 0.5, borderColor: COLORS.line, backgroundColor: "#F5F1E4" },
  cellToday: { borderWidth: 2, borderColor: COLORS.accent },
  dayNum: { fontSize: 12, color: COLORS.inkSoft },
  dayNumToday: { color: COLORS.accent, fontWeight: "700" },
  cellWeather: { position: "absolute", top: 2, right: 3, alignItems: "center" },
  cellWeatherIcon: { fontSize: 16 },
  cellWeatherTemp: { fontSize: 9, color: COLORS.inkSoft },
  dots: { position: "absolute", bottom: 4, left: 4, flexDirection: "row", gap: 3 },
  dot: { width: 6, height: 6, borderRadius: 3 },
  dotSpray: { backgroundColor: COLORS.danger },
  dotMeasure: { backgroundColor: COLORS.accent },
  dotMemo: { backgroundColor: COLORS.primary },

  legend: { flexDirection: "row", gap: 14, marginTop: 10, marginBottom: 16, flexWrap: "wrap" },
  legendItem: { flexDirection: "row", alignItems: "center", gap: 5 },
  legendText: { fontSize: 11, color: COLORS.inkSoft },

  sideCard: { backgroundColor: COLORS.surface, borderWidth: 1, borderColor: COLORS.line, borderRadius: 4, padding: 14, marginBottom: 14 },
  sideCardTitle: { fontSize: 14, fontWeight: "700", color: COLORS.ink, borderBottomWidth: 1, borderBottomColor: COLORS.line, paddingBottom: 6, marginBottom: 8 },
  statRow: { flexDirection: "row", justifyContent: "space-between", paddingVertical: 3 },
  statLabel: { fontSize: 12, color: COLORS.inkSoft },
  statValue: { fontSize: 14, fontWeight: "700", color: COLORS.ink },
  emptyNote: { fontSize: 12, color: COLORS.inkSoft },
  historyItem: { borderBottomWidth: 1, borderBottomColor: COLORS.line, borderStyle: "dashed", paddingVertical: 6 },
  historyDate: { fontSize: 11, color: COLORS.accent, fontWeight: "700" },
  historyName: { fontSize: 12, color: COLORS.ink },

  footer: { fontSize: 10, color: COLORS.inkSoft, textAlign: "center", marginTop: 8 },

  panel: { padding: 18, paddingBottom: 48 },
  panelHead: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", borderBottomWidth: 2, borderBottomColor: COLORS.ink, paddingBottom: 10, marginBottom: 14 },
  panelDate: { fontSize: 19, fontWeight: "700", color: COLORS.ink },
  closeBtn: { fontSize: 22, color: COLORS.inkSoft },
  legend2: { fontSize: 14, fontWeight: "700", color: COLORS.primaryDark, marginTop: 14, marginBottom: 8 },
  amedasBox: { backgroundColor: "#F4EFDD", borderWidth: 1, borderColor: COLORS.line, borderRadius: 4, padding: 10 },
  amedasRow: { flexDirection: "row", justifyContent: "space-between", paddingVertical: 2 },
  amedasLabel: { fontSize: 12, color: COLORS.inkSoft },
  amedasValue: { fontSize: 12, fontWeight: "700", color: COLORS.ink },
  fieldRow: { flexDirection: "row", gap: 10, marginBottom: 8 },
  fieldHalf: { flex: 1 },
  label: { fontSize: 11, color: COLORS.inkSoft, marginBottom: 3, marginTop: 4 },
  input: { borderWidth: 1, borderColor: COLORS.line, borderRadius: 4, paddingVertical: 8, paddingHorizontal: 10, fontSize: 13, backgroundColor: "#FFFEFA", color: COLORS.ink },
  textarea: { minHeight: 80, textAlignVertical: "top" },
  panelActions: { flexDirection: "row", gap: 10, marginTop: 18 },
  btn: { flex: 1, backgroundColor: COLORS.ink, borderRadius: 4, paddingVertical: 12, alignItems: "center" },
  btnText: { color: "#fff", fontSize: 13, fontWeight: "700" },
  btnSecondary: { flex: 1, borderWidth: 1, borderColor: COLORS.danger, borderRadius: 4, paddingVertical: 12, alignItems: "center" },
  btnSecondaryText: { color: COLORS.danger, fontSize: 13, fontWeight: "700" },
  saveFlash: { fontSize: 12, color: COLORS.primaryDark, textAlign: "center", marginTop: 8 },
  modalOverlay: { flex: 1, backgroundColor: "rgba(0,0,0,0.5)", justifyContent: "center", alignItems: "center", padding: 20 },
  diseaseModal: { width: "100%", maxHeight: "80%", backgroundColor: COLORS.surface, borderRadius: 8, overflow: "hidden", elevation: 5, shadowColor: "#000", shadowOpacity: 0.2, shadowRadius: 5 },
  modalHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", backgroundColor: "#FDEBD0", padding: 16, borderBottomWidth: 1, borderBottomColor: COLORS.danger },
  modalTitle: { fontSize: 18, fontWeight: "700", color: COLORS.danger },
  diseaseScroll: { padding: 16 },
  dSectionTitle: { fontSize: 13, fontWeight: "700", color: COLORS.inkSoft, marginBottom: 4, marginTop: 12 },
  dText: { fontSize: 14, color: COLORS.ink, lineHeight: 20 },
  pestCard: { backgroundColor: "#fff", borderWidth: 1, borderColor: COLORS.line, borderRadius: 6, padding: 12, marginTop: 12, marginBottom: 4 },
  pestName: { fontSize: 15, fontWeight: "700", color: COLORS.ink, marginBottom: 8 },
  pestInfoRow: { flexDirection: "row", gap: 12, marginBottom: 8 },
  pestLabel: { fontSize: 11, color: COLORS.inkSoft },
  pestValue: { fontWeight: "700", color: COLORS.primaryDark },
  pestNote: { fontSize: 12, color: COLORS.ink, backgroundColor: "#F5F1E4", padding: 8, borderRadius: 4, marginBottom: 12 },
  applyBtn: { backgroundColor: COLORS.primary, paddingVertical: 10, borderRadius: 4, alignItems: "center" },
  applyBtnText: { color: "#fff", fontSize: 13, fontWeight: "700" },
});
