import { Platform, StatusBar, StyleSheet } from "react-native";

export const COLORS = {
  bg: "#ECEFF2",
  paper: "#F8F9FA",
  surface: "#E2E7EB",
  line: "#D0D8DE",
  ink: "#2A1F2D",
  inkSoft: "#6B6470",
  leaf: "#4E6B3A",
  danger: "#A2472E",
};

const text = (size: number, color = COLORS.ink, bold = false) => ({
  fontWeight: bold ? ("700" as const) : ("400" as const),
  fontSize: size,
  color,
});

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: COLORS.bg, paddingTop: Platform.OS === "android" ? StatusBar.currentHeight : 0 },
  wrap: { padding: 16, paddingBottom: 48 },

  header: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 20 },
  title: text(22, COLORS.ink, true),
  subtitle: { ...text(13, COLORS.inkSoft), marginTop: 4 },
  weatherMini: { flexDirection: "row", alignItems: "center", gap: 8, backgroundColor: COLORS.paper, borderRadius: 4, paddingVertical: 6, paddingHorizontal: 10 },
  weatherTemp: text(17, COLORS.ink, true),
  weatherSub: text(13, COLORS.inkSoft),
  weatherStale: text(13, COLORS.danger),

  monthNav: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 10 },
  navBtn: { width: 36, height: 36, alignItems: "center", justifyContent: "center" },
  monthLabel: text(17, COLORS.ink, true),

  weekRow: { flexDirection: "row", marginBottom: 4 },
  weekLabel: { flex: 1, textAlign: "center", ...text(13, COLORS.inkSoft) },

  grid: { flexDirection: "row", flexWrap: "wrap", borderTopWidth: 1, borderLeftWidth: 1, borderColor: COLORS.line },
  cell: { width: "14.28%", height: 76, backgroundColor: COLORS.paper, borderRightWidth: 1, borderBottomWidth: 1, borderColor: COLORS.line, padding: 4 },
  cellEmpty: { width: "14.28%", height: 76, borderRightWidth: 1, borderBottomWidth: 1, borderColor: COLORS.line, backgroundColor: COLORS.surface },
  cellToday: { borderWidth: 1, borderColor: COLORS.ink },
  // 病害リスク。背景色 = その日の最も高いレベル
  cellRiskMet: { backgroundColor: "rgba(162,71,46,0.22)" },
  cellRiskNear: { backgroundColor: "rgba(162,71,46,0.09)" },
  dayNum: text(13, COLORS.inkSoft),
  dayNumToday: text(13, COLORS.ink, true),
  cellWeather: { position: "absolute", top: 4, right: 4, alignItems: "flex-end", gap: 2 },
  cellWeatherTemp: text(10, COLORS.inkSoft),
  dots: { position: "absolute", bottom: 5, left: 4, flexDirection: "row", gap: 3 },
  dot: { width: 6, height: 6, borderRadius: 3 },
  dotSpray: { backgroundColor: COLORS.danger },
  dotMemo: { backgroundColor: COLORS.leaf },

  legend: { flexDirection: "row", gap: 16, marginTop: 10, marginBottom: 28, flexWrap: "wrap" },
  legendSwatch: { width: 14, height: 14, borderRadius: 2 },
  legendItem: { flexDirection: "row", alignItems: "center", gap: 6 },
  legendText: text(13, COLORS.inkSoft),

  section: { marginBottom: 20 },
  sectionTitle: { ...text(15, COLORS.ink, true), paddingBottom: 8, borderBottomWidth: 1, borderBottomColor: COLORS.ink },
  emptyNote: { ...text(15, COLORS.inkSoft), paddingVertical: 10 },
  historyItem: { flexDirection: "row", gap: 16, borderBottomWidth: 1, borderBottomColor: COLORS.line, paddingVertical: 10 },
  historyDate: { ...text(15, COLORS.inkSoft), fontVariant: ["tabular-nums"] },
  historyName: { ...text(15), flex: 1 },

  panel: { padding: 18, paddingBottom: 48 },
  panelHead: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 8 },
  panelDate: text(22, COLORS.ink, true),
  closeBtn: { width: 36, height: 36, alignItems: "center", justifyContent: "center" },
  legend2: { ...text(15, COLORS.ink, true), marginTop: 20, paddingBottom: 6, borderBottomWidth: 1, borderBottomColor: COLORS.ink },
  tableRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", borderBottomWidth: 1, borderBottomColor: COLORS.line, paddingVertical: 8 },
  tableLabel: text(15, COLORS.inkSoft),
  tableValue: text(15),
  riskRow: { flexDirection: "row", alignItems: "center", gap: 8, borderBottomWidth: 1, borderBottomColor: COLORS.line, paddingVertical: 8 },
  riskName: { ...text(15), flex: 1 },
  riskValue: text(15, COLORS.danger, true),
  riskValueNear: text(15, COLORS.danger),
  forecastNote: { ...text(13, COLORS.inkSoft), marginTop: 6 },
  sensorHead: { flexDirection: "row", alignItems: "baseline", gap: 10, marginTop: 20, paddingBottom: 6, borderBottomWidth: 1, borderBottomColor: COLORS.ink },
  stale: text(13, COLORS.danger, true),
  fieldRow: { flexDirection: "row", gap: 10 },
  fieldHalf: { flex: 1 },
  label: { ...text(13, COLORS.inkSoft), marginBottom: 4, marginTop: 10 },
  input: { ...text(16), borderWidth: 1, borderColor: COLORS.line, borderRadius: 4, paddingVertical: 9, paddingHorizontal: 10, backgroundColor: COLORS.paper },
  textarea: { minHeight: 88, textAlignVertical: "top" },
  panelActions: { flexDirection: "row", gap: 10, marginTop: 24 },
  btn: { flex: 1, backgroundColor: COLORS.leaf, borderRadius: 4, paddingVertical: 12, alignItems: "center" },
  btnText: text(15, "#FFFFFF", true),
  btnSecondary: { flex: 1, borderWidth: 1, borderColor: COLORS.line, borderRadius: 4, paddingVertical: 12, alignItems: "center" },
  btnSecondaryText: text(15, COLORS.danger),
  saveFlash: { ...text(15, COLORS.leaf), textAlign: "center", marginTop: 10 },
  errorFlash: { ...text(15, COLORS.danger), textAlign: "center", marginTop: 10 },

  sprayRow: { flexDirection: "row", alignItems: "center", gap: 12, borderBottomWidth: 1, borderBottomColor: COLORS.line, paddingVertical: 10 },
  sprayMain: { flex: 1 },
  sprayName: text(16, COLORS.ink, true),
  sprayMeta: { ...text(13, COLORS.inkSoft), marginTop: 3 },
  rowAction: { paddingVertical: 4 },
  rowActionText: text(15, COLORS.leaf),
  rowActionDanger: text(15, COLORS.danger),
  addBtn: { marginTop: 12, borderWidth: 1, borderColor: COLORS.line, borderRadius: 4, paddingVertical: 12, alignItems: "center" },
  addBtnText: text(15, COLORS.leaf, true),
  formBox: { marginTop: 12, padding: 12, backgroundColor: COLORS.surface, borderRadius: 4 },
  pickerBtn: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", borderWidth: 1, borderColor: COLORS.line, borderRadius: 4, paddingVertical: 9, paddingHorizontal: 10, backgroundColor: COLORS.paper },
  pickerBtnText: { ...text(16), flex: 1 },
  pickerBtnPlaceholder: { ...text(16, COLORS.inkSoft), flex: 1 },
  regList: { marginTop: 8 },
  regLine: { ...text(13, COLORS.inkSoft), lineHeight: 20 },
  memoActions: { flexDirection: "row", justifyContent: "flex-end", marginTop: 10 },
  btnInline: { backgroundColor: COLORS.leaf, borderRadius: 4, paddingVertical: 10, paddingHorizontal: 18 },

  pickerWrap: { flex: 1, paddingHorizontal: 18 },
  search: { ...text(16), borderWidth: 1, borderColor: COLORS.line, borderRadius: 4, paddingVertical: 9, paddingHorizontal: 10, backgroundColor: COLORS.paper, marginTop: 8, marginBottom: 4 },
  pickerRow: { borderBottomWidth: 1, borderBottomColor: COLORS.line, paddingVertical: 12 },
  pickerMeta: { flexDirection: "row", flexWrap: "wrap", columnGap: 14, marginTop: 4 },
  sourceNote: { ...text(13, COLORS.inkSoft), marginTop: 6 },

  modalOverlay: { flex: 1, backgroundColor: "rgba(42,31,45,0.4)", justifyContent: "center", alignItems: "center", padding: 20 },
  diseaseModal: { width: "100%", maxWidth: 520, maxHeight: "80%", backgroundColor: COLORS.paper, borderRadius: 6, overflow: "hidden" },
  modalHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", paddingLeft: 18, paddingRight: 8, paddingVertical: 8, borderBottomWidth: 1, borderBottomColor: COLORS.line },
  modalTitle: text(22, COLORS.danger, true),
  diseaseScroll: { paddingHorizontal: 18, paddingBottom: 18 },
  dText: { ...text(16), lineHeight: 25, marginTop: 8 },
  pestItem: { borderBottomWidth: 1, borderBottomColor: COLORS.line, paddingVertical: 12 },
  pestName: text(16, COLORS.ink, true),
  pestInfoRow: { flexDirection: "row", flexWrap: "wrap", columnGap: 14, marginTop: 6 },
  pestLabel: text(13, COLORS.inkSoft),
  pestValue: text(13, COLORS.ink, true),
  pestNote: { ...text(15, COLORS.inkSoft), lineHeight: 22, marginTop: 6 },
  applyLink: { alignSelf: "flex-start", marginTop: 8, paddingVertical: 4 },
  applyLinkText: { ...text(15, COLORS.leaf, true), textDecorationLine: "underline" },
});
